#background color: "#BFD7ED
#font popins
#font color: "#000000"
theme:
  background_color: "#BFD7ED"
  font_family: "Poppins"
  root_color: "#1a1f2c"
  font_color: "#101627"
  accent_color: "#ffffff"
  page_color: "#ffffff"
  taskbox_color: "#ffffff"
  button_color: "#ffffff"
  button_text_color: "#101627"
  button_hover_color: "#101627"
  button_hover_text_color: "#ffffff"
  container_color: "#101627"
  task_entry_color: "#ffffff"
  add_task_color: "#ffffff"

  