theme:
  background_color: "#1C1C1E"         # Elegant dark gray background
  font_family: "Poppins"
  root_color: "#121214"              # Deeper gray for root shell
  font_color: "#E6E6EB"              # Soft off-white with cool tone
  accent_color: "#C9B6E4"            # Soft elegant lavender
  page_color: "#1F1F21"              # Section background
  taskbox_color: "#2A2A2E"           # Slight contrast for task elements
  button_color: "#C9B6E4"            # Lavender button for elegance
  button_text_color: "#1C1C1E"       # Dark text on light buttons
  button_hover_color: "#E6D9F5"      # Gentle lighter lavender on hover
  bar_button_color: "#2A2A2E"        # Sidebar/dark bar tone
  bar_button_text_color: "#C9B6E4"   # Accent for bar button text
  button_hover_text_color: "#1C1C1E"
  container_color: "#2A2A2E"         # Matches task and card containers
  task_entry_color: "#2A2A2E"
  add_task_color: "#C9B6E4"
  header_color: "#1C1C1E"
  header_text_color: "#E6E6EB"
  icon_color: "#E6E6EB"
